# Generated by Django 3.2.9 on 2022-03-04 21:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_listings'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listings',
            name='price',
        ),
    ]
